#!/bin/bash

# Some of scripts I'll use for automation combined with existing tools
# Simply automating my sensitive file leak scanning
bps() {
if [ $# -lt 1 ]; then
echo "Usage: bps <subs/domains_list> <sensitive_files_dir>"
return 1
fi

ffuf -u https://FUZZ/BUZZ -c -fs 0 -w "$1:FUZZ" -w "${2:-~/SENSITIVE}:BUZZ" -H "User-Agent: chrome"
}
