#!/bin/bash
lql() {
if [ $# -lt 1 ]; then
    echo "Usage: lql <urls_file> | lql log"
    return 1
fi

if [ "$1" == "log" ]; then
    if [ -f "lql_time_results.txt" ]; then
        cat "lql_time_results.txt"
    else
        echo "No results yet. Run LQL first."
    fi
else
    python3 "$BFH_PATH/pysrc/light_sqli_hunter.py" "$1"
fi
}
